[package]
name = "wechaty"
version = "0.1.0-beta.1"
authors = ["Gabriel Wu <qqbbnease1004@126.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Rust implementation of wechaty"
keywords = ["chatbot", "wechaty"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.12"
actix-rt = "2"
async-trait = "0.1"
futures = "0.3"
log = "0.4"
tokio = "1"
tokio-stream = "0.1"
wechaty_puppet = { version = "0.1.0-beta.1", path = "../wechaty-puppet" }

[dev-dependencies]
env_logger = "0.8"
wechaty-puppet-service = { version = "0.1.0-beta.1", path = "../wechaty-puppet-service" }

[[example]]
name = "ding-dong-bot"
path = "../examples/ding_dong_bot.rs"